#!/usr/bin/env bash
set -euo pipefail

# Online installer for Ubuntu/Debian amd64 nodes. It exchanges a short-lived
# installer token for the normal Agent credential, then keeps X-Panel secrets
# on the node's local filesystem only.

PREFIX="${XPANEL_AGENT_PREFIX:-/usr/local/bin}"
CONFIG_DIR="${XPANEL_AGENT_CONFIG_DIR:-/etc/xpanel-agent}"
DATA_DIR="${XPANEL_AGENT_DATA_DIR:-/var/lib/xpanel-agent}"
SERVICE_NAME="xpanel-agent"
RAW_BASE="${XPANEL_AGENT_RAW_BASE:-https://raw.githubusercontent.com/Arm0ne/Alien-Panel/main}"
AGENT_BINARY_URL="${XPANEL_AGENT_BINARY_URL:-$RAW_BASE/release/xpanel-agent}"
AGENT_CHECKSUM_URL="${XPANEL_AGENT_CHECKSUM_URL:-$RAW_BASE/release/xpanel-agent.sha256}"
AGENT_SERVICE_URL="${XPANEL_AGENT_SERVICE_URL:-$RAW_BASE/agent/deploy/xpanel-agent.service}"

CENTRAL_URL=""
INSTALL_TOKEN=""
XPANEL_URL="http://127.0.0.1:2053"
XPANEL_BASE_PATH="/"
AGENT_VERSION="online"

usage() {
  cat <<'EOF'
Usage:
  install-online.sh --central-url URL --install-token TOKEN [options]

Options:
  --central-url URL       Central API base URL, for example https://panel.example.com/api
  --install-token TOKEN   One-time token generated by the central panel
  --xpanel-url URL        Local X-Panel URL (default: http://127.0.0.1:2053)
  --xpanel-base-path PATH X-Panel API path (default: /)
  --agent-version VALUE   Agent version label (default: online)
  --help                  Show this help

The script supports Ubuntu/Debian amd64 with systemd. X-Panel credentials are
requested securely on the target machine and are never put in the command.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --central-url) CENTRAL_URL="${2:-}"; shift 2 ;;
    --install-token) INSTALL_TOKEN="${2:-}"; shift 2 ;;
    --xpanel-url) XPANEL_URL="${2:-}"; shift 2 ;;
    --xpanel-base-path) XPANEL_BASE_PATH="${2:-}"; shift 2 ;;
    --agent-version) AGENT_VERSION="${2:-}"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run this command as root, for example: sudo bash ..." >&2
  exit 1
fi
if [[ ! -f /etc/os-release ]]; then
  echo "Cannot identify the operating system." >&2
  exit 1
fi
# shellcheck disable=SC1091
. /etc/os-release
case "${ID:-}" in
  ubuntu|debian) ;;
  *)
    echo "This installer supports Ubuntu/Debian only; detected ${ID:-unknown}." >&2
    exit 1
    ;;
esac
case "$(uname -m)" in
  x86_64|amd64) ;;
  *) echo "This installer supports amd64 only; detected $(uname -m)." >&2; exit 1 ;;
esac
if ! command -v systemctl >/dev/null 2>&1; then
  echo "systemd is required on the target server." >&2
  exit 1
fi
if [[ -z "$CENTRAL_URL" || -z "$INSTALL_TOKEN" ]]; then
  echo "--central-url and --install-token are required." >&2
  usage >&2
  exit 2
fi
case "$CENTRAL_URL" in
  http://*|https://*) ;;
  *) echo "--central-url must include http:// or https:// and a host." >&2; exit 2 ;;
esac
case "$XPANEL_URL" in
  http://*|https://*) ;;
  *) echo "--xpanel-url must include http:// or https:// and a host." >&2; exit 2 ;;
esac
if [[ -z "$XPANEL_BASE_PATH" ]]; then XPANEL_BASE_PATH="/"; fi
if [[ "${XPANEL_BASE_PATH:0:1}" != "/" || "$XPANEL_BASE_PATH" == *"://" ]]; then
  echo "--xpanel-base-path must be a URL path beginning with /." >&2
  exit 2
fi
CENTRAL_URL="${CENTRAL_URL%/}"

need_packages=()
for command_name in curl jq sha256sum; do
  if ! command -v "$command_name" >/dev/null 2>&1; then
    need_packages+=("$command_name")
  fi
done
if [[ "${#need_packages[@]}" -gt 0 ]]; then
  echo "Installing required packages: curl jq ca-certificates"
  apt-get update
  apt-get install -y curl jq ca-certificates coreutils
fi

if [[ ! -r /dev/tty ]]; then
  echo "An interactive terminal is required to enter X-Panel credentials." >&2
  exit 2
fi
read -r -p "X-Panel username [admin]: " XPANEL_USERNAME </dev/tty
XPANEL_USERNAME="${XPANEL_USERNAME:-admin}"
read -r -s -p "X-Panel password: " XPANEL_PASSWORD </dev/tty
printf '\n' >/dev/tty
if [[ -z "$XPANEL_PASSWORD" ]]; then
  echo "X-Panel password cannot be empty." >&2
  exit 2
fi

stage="$(mktemp -d /tmp/xpanel-agent-install.XXXXXX)"
cleanup() { rm -rf "$stage"; }
trap cleanup EXIT

echo "Downloading X-Panel Agent..."
curl -fsSL --retry 3 --connect-timeout 10 --max-time 120 "$AGENT_BINARY_URL" -o "$stage/xpanel-agent"
curl -fsSL --retry 3 --connect-timeout 10 --max-time 30 "$AGENT_CHECKSUM_URL" -o "$stage/xpanel-agent.sha256"
expected_hash="$(tr -d '[:space:]\r\n' < "$stage/xpanel-agent.sha256")"
actual_hash="$(sha256sum "$stage/xpanel-agent" | awk '{print $1}')"
if [[ ! "$expected_hash" =~ ^[[:xdigit:]]{64}$ || "$expected_hash" != "$actual_hash" ]]; then
  echo "Agent checksum verification failed." >&2
  exit 1
fi
chmod 0755 "$stage/xpanel-agent"
curl -fsSL --retry 3 --connect-timeout 10 --max-time 30 "$AGENT_SERVICE_URL" -o "$stage/xpanel-agent.service"

hostname_value="$(hostname -f 2>/dev/null || hostname 2>/dev/null || true)"
bootstrap_payload="$(jq -cn --arg install_token "$INSTALL_TOKEN" --arg hostname "$hostname_value" --arg agent_version "$AGENT_VERSION" '{install_token:$install_token,hostname:$hostname,agent_version:$agent_version}')"
bootstrap_response="$stage/bootstrap.json"
bootstrap_status="$(curl -sS --connect-timeout 10 --max-time 30 -o "$bootstrap_response" -w '%{http_code}' \
  -H 'Content-Type: application/json' --data "$bootstrap_payload" "$CENTRAL_URL/agent/v1/bootstrap" || true)"
if [[ ! "$bootstrap_status" =~ ^2[0-9][0-9]$ ]]; then
  message="$(jq -r '.msg // "central bootstrap request failed"' "$bootstrap_response" 2>/dev/null || true)"
  echo "Central bootstrap failed (HTTP $bootstrap_status): $message" >&2
  exit 1
fi
bootstrap_code="$(jq -r '.code // empty' "$bootstrap_response")"
if [[ "$bootstrap_code" != "0000" ]]; then
  message="$(jq -r '.msg // "central bootstrap request failed"' "$bootstrap_response")"
  echo "Central bootstrap failed: $message" >&2
  exit 1
fi
NODE_KEY="$(jq -r '.data.node_key // empty' "$bootstrap_response")"
NODE_NAME="$(jq -r '.data.node_name // empty' "$bootstrap_response")"
NODE_TYPE="$(jq -r '.data.node_type // empty' "$bootstrap_response")"
CENTRAL_TOKEN="$(jq -r '.data.central_token // empty' "$bootstrap_response")"
if [[ -z "$NODE_KEY" || -z "$NODE_NAME" || -z "$CENTRAL_TOKEN" ]]; then
  echo "Central bootstrap returned an incomplete node credential." >&2
  exit 1
fi

yaml_quote() {
  local value="$1"
  value="$(printf '%s' "$value" | sed "s/'/''/g")"
  printf "'%s'" "$value"
}

if ! id -u xpanel-agent >/dev/null 2>&1; then
  useradd --system --home-dir "$DATA_DIR" --no-create-home --shell /usr/sbin/nologin xpanel-agent
fi
install -d -m 0755 "$PREFIX"
install -d -o xpanel-agent -g xpanel-agent -m 0750 "$DATA_DIR"
install -d -o xpanel-agent -g xpanel-agent -m 0750 "$CONFIG_DIR"

if systemctl is-active --quiet "$SERVICE_NAME.service"; then
  systemctl stop "$SERVICE_NAME.service"
fi
if [[ -f "$CONFIG_DIR/agent.yaml" ]]; then
  cp -a "$CONFIG_DIR/agent.yaml" "$CONFIG_DIR/agent.yaml.bak"
  chown xpanel-agent:xpanel-agent "$CONFIG_DIR/agent.yaml.bak"
  chmod 0600 "$CONFIG_DIR/agent.yaml.bak"
fi
if [[ -f "$PREFIX/xpanel-agent" ]]; then
  cp -a "$PREFIX/xpanel-agent" "$PREFIX/xpanel-agent.bak"
fi
install -m 0755 "$stage/xpanel-agent" "$PREFIX/xpanel-agent"
install -m 0644 "$stage/xpanel-agent.service" "/etc/systemd/system/$SERVICE_NAME.service"

config_tmp="$CONFIG_DIR/agent.yaml.tmp.$$"
umask 077
cat > "$config_tmp" <<EOF
node_key: $(yaml_quote "$NODE_KEY")
node_name: $(yaml_quote "$NODE_NAME")
node_type: $(yaml_quote "$NODE_TYPE")
central_url: $(yaml_quote "$CENTRAL_URL")
central_token: $(yaml_quote "$CENTRAL_TOKEN")
xpanel_url: $(yaml_quote "$XPANEL_URL")
xpanel_base_path: $(yaml_quote "$XPANEL_BASE_PATH")
xpanel_username: $(yaml_quote "$XPANEL_USERNAME")
xpanel_password: $(yaml_quote "$XPANEL_PASSWORD")
sync_interval: 60s
http_timeout: 15s
EOF
chown xpanel-agent:xpanel-agent "$config_tmp"
chmod 0600 "$config_tmp"
mv -f "$config_tmp" "$CONFIG_DIR/agent.yaml"

systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME.service"
if ! systemctl is-active --quiet "$SERVICE_NAME.service"; then
  echo "Agent service did not start. Run: journalctl -u $SERVICE_NAME -n 50 --no-pager" >&2
  exit 1
fi

echo
echo "X-Panel Agent installed and running in the background."
echo "Node: $NODE_NAME ($NODE_TYPE)"
echo "Service: systemctl status $SERVICE_NAME"
echo "Logs: journalctl -u $SERVICE_NAME -f"
