/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: 'dashboard',
      i18nKey: 'route.dashboard',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'events',
    path: '/events',
    component: 'layout.base$view.events',
    meta: {
      title: 'events',
      i18nKey: 'route.events',
      icon: 'mdi:bell-alert-outline',
      order: 7
    }
  },
  {
    name: 'exit-ips',
    path: '/exit-ips',
    component: 'layout.base$view.exit-ips',
    meta: {
      title: 'exit-ips',
      i18nKey: 'route.exit-ips',
      order: 4
    }
  },
  {
    name: 'finance',
    path: '/finance',
    component: 'layout.base$view.finance',
    meta: {
      title: 'finance',
      i18nKey: 'route.finance',
      icon: 'mdi:finance',
      order: 6
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'nodes',
    path: '/nodes',
    component: 'layout.base$view.nodes',
    meta: {
      title: 'nodes',
      i18nKey: 'route.nodes',
      icon: 'mdi:server-network',
      order: 3
    }
  },
  {
    name: 'nodes-detail',
    path: '/nodes/:id',
    component: 'layout.base$view.nodes-detail',
    meta: {
      title: 'nodes-detail',
      i18nKey: 'route.nodes-detail',
      hideInMenu: true,
      activeMenu: 'nodes'
    },
    props: true
  },
  {
    name: 'routes',
    path: '/routes',
    component: 'layout.base$view.routes',
    meta: {
      title: 'routes',
      i18nKey: 'route.routes',
      icon: 'mdi:source-branch',
      order: 5,
      hideInMenu: true
    }
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users',
      icon: 'mdi:account-group-outline',
      order: 2
    }
  }
];
